#
# Docker build and deployment script for Linux containers
# Based on Node.js Docker https://hub.docker.com/_/node/
# and https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
#
# Assumes we're running from within the out/ directory generated by the build.
#

FROM node:4-onbuild

# Create app directory.
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy package.json from the build and install NPM packages.
COPY package.json /usr/src/app
RUN npm install

# Copy site content from the out/site folder.
COPY ./site /usr/src/app

# Default site port
EXPOSE 8080

# Run Node.js directly (best practice to avoid additional npm process,
# see https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md).
CMD [ "node", "RunNodeSiteServer.js" ]
